### ISSUE TITLE
The generator creates bad module names when you create a project with a dash in it

### ISSUE THREAD

**Issue by oxtralite** [atomicjolt/canvas_starter_app#1]
Creating a project with the name bryan-attendance resulted in it naming the module in config/application.rb Bryan-Attendance. Rails didn't like that

**Comment by jbasdf** [comment]
Fixed by c9c073b483a9d6f4f048107949704da403bf1628

**Comment by jbasdf** [comment]
Fixed by c9c073b483a9d6f4f048107949704da403bf1628
