### ISSUE TITLE
After running the generator, the Rails asset pipeline is not generating assets  correctly

### ISSUE THREAD

**Issue by oxtralite** [atomicjolt/canvas_starter_app#3]
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
ActionController::RoutingError (No route matches [GET] "/javascripts/application.js"):

**Comment by jbasdf** [comment]
Fixed by #749a4e1a9ff38f0931e9fbba7dff362f5dc9c1c0

**Comment by jbasdf** [comment]
Fixed by #749a4e1a9ff38f0931e9fbba7dff362f5dc9c1c0
